apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2" # before cnpg-operator (-1); barman plugin needs it
spec:
  project: default
  source:
    repoURL: https://github.com/unorouter/infra.git
    targetRevision: main
    path: infra/cert-manager
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true # large CRDs
