apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: services
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/unorouter/infra.git
    targetRevision: main
    path: infra/services
  destination:
    server: https://kubernetes.default.svc
    namespace: services
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]
