apiVersion: v1
kind: Secret
metadata:
    name: newapi-pg-s3
    namespace: databases
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:K5tDI/xjR4YjtcbpBv62dme7ef8=,iv:jCF2RlTYei5g/BwN1P7A74s8yXaBo8PjbM78dQafA5k=,tag:bMPLP/Tae7TAYLwo+AF4Gg==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:c/CrLVb3gJ8c3MUGn+K+lHjsIJOj+IvASLoKSas/DCZMHbjfOcKwvA==,iv:DjMHJilILmr5oa6WWObZ9slUPNXogxr+427J/OadRXw=,tag:r5fSRkwptDl6VdQHcVe2yA==,type:str]
    REGION: ENC[AES256_GCM,data:VR4+nA==,iv:2sgmz8kEIyTZf2uDsjVbJrasc/9pohK1LtGkRT9287s=,tag:3fv2uiJ4qONZrBhaDB2Ysg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArcytGbXBSRG90K1hHVjJm
            cktZT3ZCUFRKOTZIU0ZIY2xsSmt1M3U1WlE4Ckh0c1JycjdYM2J2NDE5b2tlTDA1
            M0VOSzhGbStmL3Y5ek54YVM2U1ArVkUKLS0tIHN0bUpidkdWSTJYNm5aWHdmSzFV
            U1pjTnJqRGNUNnpCbTRnQkVOK2pqWG8KxMo9EhufgrRg/z3CphUzMeLOmdqMUc8m
            H/mLzIHF77ESmmwWK+0i5DSiM1D9eLI3wBM8QqXCddtyrCEnQUFO6Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age100xmmxguy974wt7hfud8l5efqe6ve6decfkkuynmasuny48pvajsk39pv9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T22:03:52Z"
    mac: ENC[AES256_GCM,data:AelmJZo/4lJR11cDTxl/z29N0JbJlFuEEvkMIf647+T7FshTG1diCrL4OJsN4p29WKAJ8lutXif/WyBbVSMALFa2RNYDTWg6UHLJp55lUv9VoHBe+G0JRFUxaSfWeIN+k2lvnSqgBwymxLTVZhPQdZEhok2cKRidmYnZOK+SONY=,iv:q7RQuSo6fREcUuFFwLDqgM1R56UhrlJ9zzGS9w5IYx0=,tag:DrkTo8koB9ZTqKD8ITv58Q==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: bot-pg-s3
    namespace: databases
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:5K2ngWPLDCJz4RQvgA4iG3tQ4p8=,iv:93yRl4dmM3D+mQFVtgRc+dPq63IO//+EOY3bRYrTVEo=,tag:dsbj9EHklV7wKTCneWS8ww==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:uWBhylU9me5xSoH1XzUMLOLrCd3ajrGAd7t6I/DuwPm0thPJm5FaoQ==,iv:VHZaMrz9+Wp8knVnw8xxh6lrzN4EteY4WdALhZz2MeM=,tag:ZMgSm7c+9HbKP4xsxAsl0A==,type:str]
    REGION: ENC[AES256_GCM,data:0wqHrA==,iv:xBD6LMWzCdPCs0A4LFANozIyqNBdWh8UEJYFXkWmRM0=,tag:uvI849vxwbY8n4XFh3t3lg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArcytGbXBSRG90K1hHVjJm
            cktZT3ZCUFRKOTZIU0ZIY2xsSmt1M3U1WlE4Ckh0c1JycjdYM2J2NDE5b2tlTDA1
            M0VOSzhGbStmL3Y5ek54YVM2U1ArVkUKLS0tIHN0bUpidkdWSTJYNm5aWHdmSzFV
            U1pjTnJqRGNUNnpCbTRnQkVOK2pqWG8KxMo9EhufgrRg/z3CphUzMeLOmdqMUc8m
            H/mLzIHF77ESmmwWK+0i5DSiM1D9eLI3wBM8QqXCddtyrCEnQUFO6Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age100xmmxguy974wt7hfud8l5efqe6ve6decfkkuynmasuny48pvajsk39pv9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T22:03:52Z"
    mac: ENC[AES256_GCM,data:AelmJZo/4lJR11cDTxl/z29N0JbJlFuEEvkMIf647+T7FshTG1diCrL4OJsN4p29WKAJ8lutXif/WyBbVSMALFa2RNYDTWg6UHLJp55lUv9VoHBe+G0JRFUxaSfWeIN+k2lvnSqgBwymxLTVZhPQdZEhok2cKRidmYnZOK+SONY=,iv:q7RQuSo6fREcUuFFwLDqgM1R56UhrlJ9zzGS9w5IYx0=,tag:DrkTo8koB9ZTqKD8ITv58Q==,type:str]
    version: 3.13.3
