apiVersion: v1
kind: Secret
metadata:
    name: newapi-pg-s3
    namespace: databases
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:QJJFoobX+0KfNHym1YMgaOOavDg=,iv:QHyzLJgq3t+hn/mfAeCZ0r6slrSqNPb55eo4kesjywg=,tag:JnvJpyilR1kp+Gt1OzGbBg==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:9dvaNlshIQJqcnm+014SIl3G/vy8118GEUEjabn32vdXZNGETkjyZQ==,iv:CWdLl9Ni/xD+tU1yl/5fjbvZgDlgHF+oi2OJ4KiA14c=,tag:lPc7CJfKtbocZMmY22Lsgg==,type:str]
    REGION: ENC[AES256_GCM,data:oCevdQ==,iv:3tTP1IUnwHK9fsmrgZ3lY5dblji7PEMoehqaqBnhk0s=,tag:j51L9DzC7xDLdeVT0nwgCw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2UEVKVjJQQ3ViVkhrSWRI
            K2pVbTJGUEZLZitNdDlBVEtGUk9mLzVoMEVJCnBMVEpQdzN1dHJGZStEU2NsRm5I
            WGJORzlxRXdmc092c1E2K3VXQ1RxaVEKLS0tIHVRRU1FeWRjQ0ovZWVMSXFEbU03
            K1FGdTFMSk5aMkt6MUMxTEZKOEowMTAKA15ovDbU0o5nHMTxQw+AGGWjmYcslsGG
            Afi3YP0btuzwxPKbomJ24LbHONCCtokt2hRGAPcUPpVoQj/rxVd2Bg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age100xmmxguy974wt7hfud8l5efqe6ve6decfkkuynmasuny48pvajsk39pv9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T18:00:01Z"
    mac: ENC[AES256_GCM,data:e0Bph1e33x+uFDKaK8xfTNAaTFv1gdmfWaKMgxnhU9zXkEP6lkouXQt4CWgEbHME2fiM91KBfDNToxlwfQs8Fw3h1rXFba8wgkhLfLmRcbTR81zA2ouZTVUCxZMM9Jv61NiIA6x879ncmw7nDmlGT61ZZ51KjzNpvWwSzjhTI8k=,iv:vQZyOvddZNvNT37qp89KzjQ7eulSTxNAXE4Ur41dtPw=,tag:6qiFc2TuTBExSGVEjObLSw==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: bot-pg-s3
    namespace: databases
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:SvfisFZTEFMo5EiJE+85thwSHMg=,iv:Rb/7a+9HMdxGN4+MJSpxfoHK4jHZPbieLnLhb1B02lE=,tag:ltQ+84GHpJg9vKQdYT4b+Q==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:3uAWwwmINKTrjsSFhFQ/POCTMWH65er0kCwlGmi4XN/UMn1xMqg0LQ==,iv:6JQTQ1sHzoMmIO4VCVp4t/pLOrCJdcUIZsfR4qMWGsE=,tag:MeJdqLQpxPQeG3a8SkagyQ==,type:str]
    REGION: ENC[AES256_GCM,data:jcIngQ==,iv:pUXcqeoFRh7FkoEBditU/4X7ZoQlq7hP2ZZL+2EFgWQ=,tag:kb9kQgDxfiAwPD2jbMTyzQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2UEVKVjJQQ3ViVkhrSWRI
            K2pVbTJGUEZLZitNdDlBVEtGUk9mLzVoMEVJCnBMVEpQdzN1dHJGZStEU2NsRm5I
            WGJORzlxRXdmc092c1E2K3VXQ1RxaVEKLS0tIHVRRU1FeWRjQ0ovZWVMSXFEbU03
            K1FGdTFMSk5aMkt6MUMxTEZKOEowMTAKA15ovDbU0o5nHMTxQw+AGGWjmYcslsGG
            Afi3YP0btuzwxPKbomJ24LbHONCCtokt2hRGAPcUPpVoQj/rxVd2Bg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age100xmmxguy974wt7hfud8l5efqe6ve6decfkkuynmasuny48pvajsk39pv9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T18:00:01Z"
    mac: ENC[AES256_GCM,data:e0Bph1e33x+uFDKaK8xfTNAaTFv1gdmfWaKMgxnhU9zXkEP6lkouXQt4CWgEbHME2fiM91KBfDNToxlwfQs8Fw3h1rXFba8wgkhLfLmRcbTR81zA2ouZTVUCxZMM9Jv61NiIA6x879ncmw7nDmlGT61ZZ51KjzNpvWwSzjhTI8k=,iv:vQZyOvddZNvNT37qp89KzjQ7eulSTxNAXE4Ur41dtPw=,tag:6qiFc2TuTBExSGVEjObLSw==,type:str]
    version: 3.13.3
