apiVersion: v1
kind: Secret
metadata:
    name: newapi-pg-s3
    namespace: databases
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:qHpXA/xvD2Q8ozJ6lJdV7awFfZc=,iv:7HSxpqUEEnCxto34HZfFkpouC5R/MfvI+dU9lWZ5xtc=,tag:FI4ots9kMJGDq9MHiuot0Q==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:eDzsIDCmvtqjSaUVLjwECMN/ZkhHRtY3mSFlBS4qXzufoEW4u/qq0w==,iv:S3jO5KVdmx67/o6n+x/TnXtniHF2rLiJgJIILEZZfZ0=,tag:UKqSxGY9T+jLAQRoxY310A==,type:str]
    REGION: ENC[AES256_GCM,data:HlDjQA==,iv:PiVm75ymedXBtvPf4qQn/FMDMuqCPcI+cYQy5VDP6kg=,tag:XsfHUqVgXAxZsIFnXlvsUQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBScFIyN09zVE0wajlsY09T
            aUU2ZTJCQ3JCQ1FveXFvNUZ1TDErMGFQWW1JCmkxSnRKdTlXTUE1MWM2OVVDVG40
            VjJQajlYa05qVDBEcmpkUXMrR0JIRWMKLS0tIHFaUDlnaTRJY2ZtZWRzRTUrTVk0
            N252Z2crajE5SVVaR1lmNE00Q3pyeVEKT8WDcFHpk2F/ZXE/Zt8H2yYRpM6gSTpt
            LhIV1AC5YoMRRB47Y1+p/bJeoXefwcRkpgeGqSewn/wP05V13eHDdQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age100xmmxguy974wt7hfud8l5efqe6ve6decfkkuynmasuny48pvajsk39pv9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-21T22:15:03Z"
    mac: ENC[AES256_GCM,data:EbvL9BylkS/YRojAdEP15P5rmv1BVY1ym3er+9kFHy8HwI9Yr3xGxrBons2KengXAM7K2ae3UN6K9e+pGHSX6zv/slsRLRJpHyBtvtwdf14CB1CyoRCuPzhWtjVSYH2m0s96Jj3DGZIyM3ijDbUPYXrJh/VfYoU+r0FY8kCMvWs=,iv:0Lf68As0AV4vnmKfI3HUNGTt2KVmMuE1jQHIziwUMQE=,tag:cMrCl4wdmo3iqSEpNeWPaA==,type:str]
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: bot-pg-s3
    namespace: databases
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:d8EzEyhET+0HdFbohsRCKZBFvuA=,iv:A2ZR4qsfyeD3pq48XnRL1GYw5EqqnU95GTjM93UMmTs=,tag:4bwn5/LynvwyKFR6u+BfYQ==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:m1sCfhf/ClTQ8kB6tV0BClXPGAhsvUOzVhUGNWIu0g7x0S8oio4Tvw==,iv:lUi4CUM6b4WQc18wyI2Yp/BSKQu/2GFsozboYzRcKiY=,tag:yd8UPhAKR7VwIP8si8WUvw==,type:str]
    REGION: ENC[AES256_GCM,data:+LZQQQ==,iv:cMrQ8umgb0rm3F8YkCMJpTrj8gXBnDF1rPqZNJOqRGs=,tag:Kvm/+ALVOSMwm2upOYFcsg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBScFIyN09zVE0wajlsY09T
            aUU2ZTJCQ3JCQ1FveXFvNUZ1TDErMGFQWW1JCmkxSnRKdTlXTUE1MWM2OVVDVG40
            VjJQajlYa05qVDBEcmpkUXMrR0JIRWMKLS0tIHFaUDlnaTRJY2ZtZWRzRTUrTVk0
            N252Z2crajE5SVVaR1lmNE00Q3pyeVEKT8WDcFHpk2F/ZXE/Zt8H2yYRpM6gSTpt
            LhIV1AC5YoMRRB47Y1+p/bJeoXefwcRkpgeGqSewn/wP05V13eHDdQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age100xmmxguy974wt7hfud8l5efqe6ve6decfkkuynmasuny48pvajsk39pv9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-21T22:15:03Z"
    mac: ENC[AES256_GCM,data:EbvL9BylkS/YRojAdEP15P5rmv1BVY1ym3er+9kFHy8HwI9Yr3xGxrBons2KengXAM7K2ae3UN6K9e+pGHSX6zv/slsRLRJpHyBtvtwdf14CB1CyoRCuPzhWtjVSYH2m0s96Jj3DGZIyM3ijDbUPYXrJh/VfYoU+r0FY8kCMvWs=,iv:0Lf68As0AV4vnmKfI3HUNGTt2KVmMuE1jQHIziwUMQE=,tag:cMrCl4wdmo3iqSEpNeWPaA==,type:str]
    version: 3.13.2
