apiVersion: v1
kind: Secret
metadata:
    name: newapi-pg-s3
    namespace: databases
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:7lsCvwdq6whGSF2RAlBnWKeX4D0=,iv:otUTLXuAdoQSh8dzlgl8hfTWNLLAyU5rENwRcc02UAM=,tag:4YUlORPvzOBLK3jD6updDQ==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:ZA7gdGCpMM4qbGETSw0W5iX4f8NEAJhVwy8somJnk2oiOVzYNJCn7w==,iv:mcytBqYMGiyGs7Reyf8To2ZIBGvwNl3SDpShPIyYjbg=,tag:kYbGC1RM0bsK5DkAjiCY+g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOK25NL2lHRXRlcGtvNFZ2
            dFhLdlQ1c3k4RlVWOFUyRDF2UTVJR3REclRZCkN3TjYxeVIzamlFQUZNc2Ezekg1
            L0ZzZHFKVHpxeWpUNzFTemYyRzBSbzQKLS0tIDViRXkzdkl2cklUcm1vODlLK2NH
            L2xib1AyZzMrYTRHV2NZNmRWTzZFenMKG+vu2TueJDzIB0wJDvMYETwLY5Xy1Gtr
            cWFNCKSQBiCzSdBEygml1fW/SBJqVkhhm8brhk9UKH2kHjKvKFOesw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age100xmmxguy974wt7hfud8l5efqe6ve6decfkkuynmasuny48pvajsk39pv9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-21T21:49:45Z"
    mac: ENC[AES256_GCM,data:ExXuOIryWdnoRHfThk6bJbk0McuFkrJAWcn7YSNMDevCLtzvoLImxxzYC6uwYvmRuEZNhtpKixlxITuLv0So/5CVjUa3TAWQsMw/Kywv+txu8vr/jEJmtvPFQGU5815X9IjXETG88hIt3JohtRKGluql7izthV2Ik1XRukq71iM=,iv:WEj/t+wLSM+IJED1T6nQzleHel25/KaDWDJJ7HLWdeU=,tag:Fc8Qta9vX/9mWi9RRgEslg==,type:str]
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: bot-pg-s3
    namespace: databases
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:UfF1CKcLayzLmb+K36EJKveLPKw=,iv:VY6q8sP6vAywz93vDTx7lgzxABKe0kDC7jujz1UJ4PA=,tag:64vp7GC4ca+amdrFyh0V3A==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:qD48PN45fBjB+YWTq/b/7dhQa9v0gK5u5iDjQMreTrDBigRtcmc/CQ==,iv:IOFiF48MZH0zUMAy+kvTncc/GZ4ZofzgvYisPsN3pf0=,tag:w9D3LtfEV2Bb69X8fyLWqQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOK25NL2lHRXRlcGtvNFZ2
            dFhLdlQ1c3k4RlVWOFUyRDF2UTVJR3REclRZCkN3TjYxeVIzamlFQUZNc2Ezekg1
            L0ZzZHFKVHpxeWpUNzFTemYyRzBSbzQKLS0tIDViRXkzdkl2cklUcm1vODlLK2NH
            L2xib1AyZzMrYTRHV2NZNmRWTzZFenMKG+vu2TueJDzIB0wJDvMYETwLY5Xy1Gtr
            cWFNCKSQBiCzSdBEygml1fW/SBJqVkhhm8brhk9UKH2kHjKvKFOesw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age100xmmxguy974wt7hfud8l5efqe6ve6decfkkuynmasuny48pvajsk39pv9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-21T21:49:45Z"
    mac: ENC[AES256_GCM,data:ExXuOIryWdnoRHfThk6bJbk0McuFkrJAWcn7YSNMDevCLtzvoLImxxzYC6uwYvmRuEZNhtpKixlxITuLv0So/5CVjUa3TAWQsMw/Kywv+txu8vr/jEJmtvPFQGU5815X9IjXETG88hIt3JohtRKGluql7izthV2Ik1XRukq71iM=,iv:WEj/t+wLSM+IJED1T6nQzleHel25/KaDWDJJ7HLWdeU=,tag:Fc8Qta9vX/9mWi9RRgEslg==,type:str]
    version: 3.13.2
